package com.example.drivecoach.model

data class Lesson(
    var id: String = "",              // A unique identifier of the class that will be generated by Firebase.
    var instructorId: String = "",
    var studentId: String = "",
    var studentName: String = "",
    var date: String = "",
    var time: String = "",
    var location: String = "",
    var completed: Boolean = false
)